name: SBOM-Automation-Lab

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 코드를 서버로 가져오기
        uses: actions/checkout@v3

      - name: SBOM 생성 (Syft)
        uses: anchore/sbom-action@v0
        with:
          format: spdx-json
          output-file: "my-app.sbom.json"

      - name: 취약점 스캔하기 (Grype)
        uses: anchore/scan-action@v3
        with:
          sbom: "my-app.sbom.json"
          fail-build: false
          db-update: true # <--- 이 줄을 추가해서 최신 취약점 정보를 가져오게 합니다!
